# Auth:
#   Authorizers:
#     OAuth2Authorizer:
#       JwtConfiguration:
#         issuer: "https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_uBI3rxuig" https://cognito-idp.{region}.amazonaws.com/{user_pool_id}
#  https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_frOcvpAOE
# client id: 7fu4th73qti0sgbe4bra9r7ou0
#         audience:
#           - !Ref UiUserPoolClientId
#       IdentitySource: "$request.header.Authorization"

Authorizer:
  Type: AWS::ApiGateway::Authorizer
  Properties:
    ApiId: !Ref ApiGatewayHttpApi
    Name: MyCognitoAuthorizer
    Type: COGNITO_USER_POOLS
    IdentitySource: method.request.header.Authorization
    RestApiId: !Ref ApiGatewayHttpApi
    ProviderARNs:
      - arn:aws:cognito-idp:eu-west-1:your-account-id:userpool/your-user-pool-id
# CognitoUserPoolAuthorizer:
#   Type: AWS::ApiGatewayV2::Authorizer
#   Properties:
#     Name: CognitoAuthorizer
#     ApiId: !Ref ApiGatewayHttpApi
#     AuthorizerType: JWT
#     IdentitySource:
#       - "$request.header.Authorization"
#     JwtConfiguration:
#       Audience:
#         - !Ref CognitoUserPoolClient
#       Issuer: !ImportValue krisu-auth-app---user-pool-provider-url
